name: Build and Release

on:
  push:
    tags:
      - 'v*'
      - '*beta*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew       
      
      - name: build
        run: ./gradlew build

      - name: upload
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          version: ${{ github.ref_name }}
          changelog-file: CHANGELOG.md

          modrinth-id: L0g6pT9H
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-files: build/libs/!(*-@(dev|sources|javadoc)).jar

          curseforge-id: 1602408
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-files: build/libs/!(*-@(dev|sources|javadoc)).jar

          github-token: ${{ secrets.RELEASE_TOKEN }}
          github-files: build/libs/*.jar

          dependencies: |
            YetAnotherConfigLib@3.9.6+26.2-fabric(required){modrinth:1eAoo2KR}{curseforge:667299}#(ignore:github)
            fabric-api@0.156.0+26.2(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            Mod Menu@20.0.1(optional){modrinth:mOgUt4GM}{curseforge:308702}#(ignore:github)