name: Build and Release

on:
  push:
    tags:
      - 'v*'
      - 'Beta*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew       
      
      - name: build
        run: ./gradlew build
      
      - name: Determine release type
        id: release-type
        run: |
          if [[ "${{ github.ref_name }}" == beta* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      
      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release-type.outputs.release_name }}
          prerelease: ${{ steps.release-type.outputs.is_prerelease }}
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}